'use client';

import { useState, useEffect, useRef } from 'react';
import { useParams } from 'next/navigation';
import { getDictionaryClient } from '@/app/[tenant]/[lang]/dictionaries-client';

interface Product {
  _id?: string;
  name: string;
  description?: string;
  price: number;
  stock: number;
  sku?: string;
  category?: string;
  trackInventory?: boolean;
  allowOutOfStockSales?: boolean;
}

interface ProductModalProps {
  product: Product | null;
  onClose: () => void;
  lang?: 'en' | 'es';
}

const generateSKU = (name: string): string => {
  if (!name || name.trim().length === 0) return '';
  
  // Get first 3 letters (uppercase), remove spaces and special chars
  const cleanName = name.replace(/[^a-zA-Z0-9]/g, '').toUpperCase();
  const prefix = cleanName.substring(0, 3).padEnd(3, 'X');
  
  // Add timestamp suffix (last 6 digits)
  const suffix = Date.now().toString().slice(-6);
  
  return `${prefix}-${suffix}`;
};

export default function ProductModal({ product, onClose, lang = 'en' }: ProductModalProps) {
  const params = useParams();
  const tenant = (params?.tenant as string) || 'default';
  const [dict, setDict] = useState<any>(null);
  const [categories, setCategories] = useState<string[]>([]);
  const [showCategorySuggestions, setShowCategorySuggestions] = useState(false);
  const [filteredCategories, setFilteredCategories] = useState<string[]>([]);
  const categoryInputRef = useRef<HTMLInputElement>(null);
  const categoryListRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    getDictionaryClient(lang).then(setDict);
  }, [lang]);

  useEffect(() => {
    // Fetch existing categories from products
    const fetchCategories = async () => {
      try {
        const res = await fetch(`/api/products?tenant=${tenant}`);
        const data = await res.json();
        if (data.success && data.data) {
          // Extract unique categories
          const uniqueCategories = Array.from(
            new Set(
              data.data
                .map((p: Product) => p.category)
                .filter((cat: string | undefined) => cat && cat.trim() !== '')
            )
          ) as string[];
          setCategories(uniqueCategories.sort());
        }
      } catch (error) {
        console.error('Error fetching categories:', error);
      }
    };
    fetchCategories();
  }, [tenant]);

  const [formData, setFormData] = useState({
    name: '',
    description: '',
    price: '',
    stock: '',
    sku: '',
    category: '',
    trackInventory: true,
    allowOutOfStockSales: false,
  });
  const [loading, setLoading] = useState(false);
  const [skuAutoGenerated, setSkuAutoGenerated] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});

  useEffect(() => {
    if (product) {
      // Ensure boolean values are properly set
      const trackInventory = product.trackInventory === false ? false : true;
      const allowOutOfStockSales = product.allowOutOfStockSales === true ? true : false;
      
      setFormData({
        name: product.name || '',
        description: product.description || '',
        price: product.price?.toString() || '',
        stock: product.stock?.toString() || '',
        sku: product.sku || '',
        category: product.category || '',
        trackInventory,
        allowOutOfStockSales,
      });
      setSkuAutoGenerated(false);
      setErrors({}); // Clear errors when loading product
    } else {
      // Reset form for new product
      setFormData({
        name: '',
        description: '',
        price: '',
        stock: '',
        sku: '',
        category: '',
        trackInventory: true,
        allowOutOfStockSales: false,
      });
      setSkuAutoGenerated(false);
      setErrors({}); // Clear errors when resetting form
    }
  }, [product?._id, product?.trackInventory, product?.allowOutOfStockSales]);

  // Auto-generate SKU when name changes (only for new products, only once)
  useEffect(() => {
    if (!product && formData.name && !formData.sku && !skuAutoGenerated) {
      const generatedSKU = generateSKU(formData.name);
      setFormData(prev => ({ ...prev, sku: generatedSKU }));
      setSkuAutoGenerated(true);
    }
  }, [formData.name, formData.sku, product, skuAutoGenerated]);

  // Filter categories based on input
  useEffect(() => {
    if (formData.category.trim() === '') {
      setFilteredCategories(categories);
    } else {
      const filtered = categories.filter(cat =>
        cat.toLowerCase().includes(formData.category.toLowerCase())
      );
      setFilteredCategories(filtered);
    }
  }, [formData.category, categories]);

  const handleCategorySelect = (category: string) => {
    setFormData(prev => ({ ...prev, category }));
    setShowCategorySuggestions(false);
    categoryInputRef.current?.blur();
  };

  // Handle click outside to close suggestions
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (
        categoryInputRef.current &&
        categoryListRef.current &&
        !categoryInputRef.current.contains(event.target as Node) &&
        !categoryListRef.current.contains(event.target as Node)
      ) {
        setShowCategorySuggestions(false);
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setErrors({});

    try {
      const url = product?._id 
        ? `/api/products/${product._id}?tenant=${tenant}` 
        : `/api/products?tenant=${tenant}`;
      const method = product?._id ? 'PUT' : 'POST';
      
      // Client-side validation
      const validationErrors: Record<string, string> = {};
      
      if (!formData.name.trim()) {
        validationErrors.name = dict?.products?.nameRequired || 'Product name is required';
      } else if (formData.name.length > 200) {
        validationErrors.name = dict?.products?.nameTooLong || 'Product name must be less than 200 characters';
      }
      
      const priceInput = formData.price.trim();
      if (!priceInput) {
        validationErrors.price = dict?.products?.invalidPrice || 'Price is required';
      } else {
        const price = parseFloat(priceInput);
        if (isNaN(price) || price < 0) {
          validationErrors.price = dict?.products?.invalidPrice || 'Please enter a valid price';
        }
      }
      
      const stockInput = formData.stock.trim();
      let stockNum = 0;
      if (!stockInput) {
        validationErrors.stock = dict?.products?.invalidStock || 'Stock quantity is required';
      } else {
        stockNum = parseInt(stockInput, 10);
        if (isNaN(stockNum) || stockNum < 0 || stockNum.toString() !== stockInput) {
          validationErrors.stock = dict?.products?.invalidStock || 'Please enter a valid stock quantity (must be a whole number)';
        }
      }
      
      if (formData.sku && formData.sku.trim().length > 50) {
        validationErrors.sku = dict?.products?.skuTooLong || 'SKU must be less than 50 characters';
      }
      
      if (Object.keys(validationErrors).length > 0) {
        setErrors(validationErrors);
        setLoading(false);
        return;
      }
      
      const priceValue = parseFloat(formData.price.trim());
      
      const submitData: any = {
        name: formData.name.trim(),
        description: formData.description?.trim() || undefined,
        price: priceValue,
        stock: stockNum,
        sku: formData.sku?.trim() || undefined,
        category: formData.category?.trim() || undefined,
        trackInventory: Boolean(formData.trackInventory),
        allowOutOfStockSales: Boolean(formData.allowOutOfStockSales),
      };
      
      const res = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(submitData),
      });

      const data = await res.json();
      if (data.success) {
        onClose();
      } else {
        // Handle validation errors from API
        if (data.errors && Array.isArray(data.errors)) {
          const apiErrors: Record<string, string> = {};
          data.errors.forEach((err: any) => {
            if (err.field) {
              apiErrors[err.field] = err.message;
            }
          });
          setErrors(apiErrors);
        } else {
          // Check if error is related to SKU duplicate
          const errorMessage = data.error || (dict?.products.saveError || 'Failed to save product');
          if (errorMessage.toLowerCase().includes('sku') || errorMessage.toLowerCase().includes('already exists')) {
            setErrors({ sku: errorMessage, general: errorMessage });
          } else {
            setErrors({ general: errorMessage });
          }
        }
      }
    } catch (error) {
      console.error('Error saving product:', error);
      setErrors({ general: dict?.products.saveError || 'Failed to save product' });
    } finally {
      setLoading(false);
    }
  };

  if (!dict) {
    return null;
  }

  return (
    <div 
      className="fixed inset-0 bg-gray-900/30 backdrop-blur-md z-50"
      onClick={onClose}
    >
      <div 
        className="absolute inset-y-0 right-0 w-full max-w-md bg-white border-l border-gray-300 flex flex-col animate-slide-in-right"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between p-5 sm:p-6 border-b border-gray-200">
          <h2 className="text-xl sm:text-2xl font-bold text-gray-900">
            {product ? dict.products.editProduct : dict.products.addProduct}
          </h2>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 transition-colors"
          >
            <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        <div className="flex-1 overflow-y-auto p-5 sm:p-6">
        <form onSubmit={handleSubmit} className="space-y-4">
          {errors.general && (
            <div className="p-3 bg-red-50 border border-red-300">
              <p className="text-sm text-red-600">{errors.general}</p>
            </div>
          )}
          
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              {dict.products.name} *
            </label>
            <input
              type="text"
              required
              value={formData.name}
              onChange={(e) => {
                setFormData(prev => ({ ...prev, name: e.target.value }));
                if (errors.name) setErrors(prev => ({ ...prev, name: '' }));
              }}
              className={`w-full px-3 py-2.5 text-base border focus:ring-2 focus:ring-blue-500 bg-white ${
                errors.name ? 'border-red-300 focus:ring-red-500' : 'border-gray-300'
              }`}
            />
            {errors.name && (
              <p className="mt-1 text-sm text-red-600">{errors.name}</p>
            )}
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              {dict.products.description}
            </label>
            <textarea
              value={formData.description}
              onChange={(e) => setFormData(prev => ({ ...prev, description: e.target.value }))}
              className="w-full px-3 py-2.5 text-base border border-gray-300 focus:ring-2 focus:ring-blue-500 bg-white"
              rows={3}
            />
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                {dict.products.price} *
              </label>
              <input
                type="number"
                step="0.01"
                min="0"
                required
                value={formData.price}
                onChange={(e) => {
                  const value = e.target.value;
                  // Allow empty string, or valid numbers (including decimals)
                  if (value === '' || /^\d*\.?\d*$/.test(value)) {
                    setFormData(prev => ({ ...prev, price: value }));
                    if (errors.price) setErrors(prev => ({ ...prev, price: '' }));
                  }
                }}
                className={`w-full px-3 py-2.5 text-base border focus:ring-2 focus:ring-blue-500 bg-white ${
                  errors.price ? 'border-red-300 focus:ring-red-500' : 'border-gray-300'
                }`}
              />
              {errors.price && (
                <p className="mt-1 text-sm text-red-600">{errors.price}</p>
              )}
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                {dict.products.stock} *
              </label>
              <input
                type="number"
                min="0"
                required
                value={formData.stock}
                onChange={(e) => {
                  const value = e.target.value;
                  // Allow empty string, or valid non-negative integers
                  if (value === '' || /^\d+$/.test(value)) {
                    setFormData(prev => ({ ...prev, stock: value }));
                    if (errors.stock) setErrors(prev => ({ ...prev, stock: '' }));
                  }
                }}
                className={`w-full px-3 py-2.5 text-base border focus:ring-2 focus:ring-blue-500 bg-white ${
                  errors.stock ? 'border-red-300 focus:ring-red-500' : 'border-gray-300'
                }`}
              />
              {errors.stock && (
                <p className="mt-1 text-sm text-red-600">{errors.stock}</p>
              )}
            </div>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              {dict.products.sku}
            </label>
            <div className="flex gap-2">
              <input
                type="text"
                value={formData.sku}
                onChange={(e) => {
                  setFormData(prev => ({ ...prev, sku: e.target.value }));
                  setSkuAutoGenerated(false);
                  if (errors.sku) setErrors(prev => ({ ...prev, sku: '' }));
                }}
                className={`flex-1 px-3 py-2.5 text-base border focus:ring-2 focus:ring-blue-500 bg-white ${
                  errors.sku ? 'border-red-300 focus:ring-red-500' : 'border-gray-300'
                }`}
                placeholder={!product ? (dict?.products?.autoGenerated || 'Auto-generated') : ''}
              />
              {!product && (
                <button
                  type="button"
                  onClick={() => {
                    const generatedSKU = generateSKU(formData.name || 'PRO');
                    setFormData(prev => ({ ...prev, sku: generatedSKU }));
                    setSkuAutoGenerated(true);
                  }}
                  className="px-3 py-2.5 bg-gray-100 text-gray-700 hover:bg-gray-200 transition-colors text-sm font-medium border border-gray-300"
                  title={dict?.products?.regenerateSKU || 'Regenerate SKU'}
                >
                  <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                  </svg>
                </button>
              )}
            </div>
            {errors.sku && (
              <p className="mt-1 text-sm text-red-600">{errors.sku}</p>
            )}
          </div>
          <div className="relative">
            <label className="block text-sm font-medium text-gray-700 mb-1">
              {dict.products.category}
            </label>
            <div ref={categoryInputRef} className="relative">
              <input
                type="text"
                value={formData.category}
                onChange={(e) => {
                  setFormData(prev => ({ ...prev, category: e.target.value }));
                  setShowCategorySuggestions(true);
                  if (errors.category) setErrors(prev => ({ ...prev, category: '' }));
                }}
                onFocus={() => setShowCategorySuggestions(true)}
                className={`w-full px-3 py-2.5 text-base border focus:ring-2 focus:ring-blue-500 bg-white ${
                  errors.category ? 'border-red-300 focus:ring-red-500' : 'border-gray-300'
                }`}
                placeholder={dict?.products?.typeToSearchOrSelect || 'Type to search or select...'}
              />
              {errors.category && (
                <p className="mt-1 text-sm text-red-600">{errors.category}</p>
              )}
              {showCategorySuggestions && filteredCategories.length > 0 && (
                <div
                  ref={categoryListRef}
                  className="absolute z-10 w-full mt-1 bg-white border border-gray-300 max-h-60 overflow-y-auto"
                >
                  {filteredCategories.map((cat, index) => (
                    <button
                      key={index}
                      type="button"
                      onClick={() => handleCategorySelect(cat)}
                      className="w-full text-left px-4 py-2 hover:bg-blue-50 focus:bg-blue-50 focus:outline-none transition-colors"
                    >
                      {cat}
                    </button>
                  ))}
                </div>
              )}
            </div>
          </div>
          
          {/* Inventory Settings */}
          <div className="border-t border-gray-200 pt-4 space-y-4">
            <h3 className="text-sm font-semibold text-gray-700 mb-3">
              {dict?.products?.inventorySettings || 'Inventory Settings'}
            </h3>
            
            <div className="flex items-start gap-3">
              <input
                type="checkbox"
                id="trackInventory"
                checked={formData.trackInventory === true}
                onChange={(e) => {
                  setFormData(prev => ({ ...prev, trackInventory: e.target.checked }));
                }}
                className="mt-1 h-4 w-4 border-gray-300 text-blue-600 focus:ring-2 focus:ring-blue-500"
              />
              <div className="flex-1">
                <label 
                  htmlFor="trackInventory"
                  className="block text-sm font-medium text-gray-700 mb-1 cursor-pointer"
                >
                  {dict?.products?.trackInventory || 'Track Inventory'}
                </label>
                <p className="text-xs text-gray-500">
                  {dict?.products?.trackInventoryDesc || 'Enable stock tracking for this product'}
                </p>
              </div>
            </div>
            
            <div className="flex items-start gap-3">
              <input
                type="checkbox"
                id="allowOutOfStockSales"
                checked={formData.allowOutOfStockSales === true}
                onChange={(e) => {
                  setFormData(prev => ({ ...prev, allowOutOfStockSales: e.target.checked }));
                }}
                className="mt-1 h-4 w-4 border-gray-300 text-blue-600 focus:ring-2 focus:ring-blue-500"
              />
              <div className="flex-1">
                <label 
                  htmlFor="allowOutOfStockSales"
                  className="block text-sm font-medium text-gray-700 mb-1 cursor-pointer"
                >
                  {dict?.products?.allowOutOfStockSales || 'Allow Sales When Out of Stock'}
                </label>
                <p className="text-xs text-gray-500">
                  {dict?.products?.allowOutOfStockSalesDesc || 'Allow customers to purchase this product even when stock is 0'}
                </p>
              </div>
            </div>
          </div>
          
          <div className="flex flex-col sm:flex-row justify-end gap-2 pt-4">
            <button
              type="button"
              onClick={onClose}
              className="w-full sm:w-auto px-4 py-2.5 border border-gray-300 text-gray-700 hover:bg-gray-50 active:bg-gray-100 font-medium bg-white"
            >
              {dict.common.cancel}
            </button>
            <button
              type="submit"
              disabled={loading}
              className="w-full sm:w-auto px-4 py-2.5 bg-blue-600 text-white hover:bg-blue-700 active:bg-blue-800 disabled:opacity-50 disabled:cursor-not-allowed font-medium border border-blue-700"
            >
              {loading ? dict.common.loading : dict.common.save}
            </button>
          </div>
        </form>
        </div>
      </div>
    </div>
  );
}

