'use client';

import { useState, useEffect, useRef } from 'react';
import { useParams } from 'next/navigation';
import { getDictionaryClient } from '@/app/[tenant]/[lang]/dictionaries-client';

interface Product {
  _id?: string;
  name: string;
  description?: string;
  price: number;
  stock: number;
  sku?: string;
  category?: string;
}

interface ProductModalProps {
  product: Product | null;
  onClose: () => void;
  lang?: 'en' | 'es';
}

const generateSKU = (name: string): string => {
  if (!name || name.trim().length === 0) return '';
  
  // Get first 3 letters (uppercase), remove spaces and special chars
  const cleanName = name.replace(/[^a-zA-Z0-9]/g, '').toUpperCase();
  const prefix = cleanName.substring(0, 3).padEnd(3, 'X');
  
  // Add timestamp suffix (last 6 digits)
  const suffix = Date.now().toString().slice(-6);
  
  return `${prefix}-${suffix}`;
};

export default function ProductModal({ product, onClose, lang = 'en' }: ProductModalProps) {
  const params = useParams();
  const tenant = (params?.tenant as string) || 'default';
  const [dict, setDict] = useState<any>(null);
  const [categories, setCategories] = useState<string[]>([]);
  const [showCategorySuggestions, setShowCategorySuggestions] = useState(false);
  const [filteredCategories, setFilteredCategories] = useState<string[]>([]);
  const categoryInputRef = useRef<HTMLInputElement>(null);
  const categoryListRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    getDictionaryClient(lang).then(setDict);
  }, [lang]);

  useEffect(() => {
    // Fetch existing categories from products
    const fetchCategories = async () => {
      try {
        const res = await fetch(`/api/products?tenant=${tenant}`);
        const data = await res.json();
        if (data.success && data.data) {
          // Extract unique categories
          const uniqueCategories = Array.from(
            new Set(
              data.data
                .map((p: Product) => p.category)
                .filter((cat: string | undefined) => cat && cat.trim() !== '')
            )
          ) as string[];
          setCategories(uniqueCategories.sort());
        }
      } catch (error) {
        console.error('Error fetching categories:', error);
      }
    };
    fetchCategories();
  }, [tenant]);

  const [formData, setFormData] = useState({
    name: '',
    description: '',
    price: '',
    stock: '',
    sku: '',
    category: '',
  });
  const [loading, setLoading] = useState(false);
  const [skuAutoGenerated, setSkuAutoGenerated] = useState(false);

  useEffect(() => {
    if (product) {
      setFormData({
        name: product.name || '',
        description: product.description || '',
        price: product.price?.toString() || '',
        stock: product.stock?.toString() || '',
        sku: product.sku || '',
        category: product.category || '',
      });
      setSkuAutoGenerated(false);
    } else {
      // Reset form for new product
      setFormData({
        name: '',
        description: '',
        price: '',
        stock: '',
        sku: '',
        category: '',
      });
      setSkuAutoGenerated(false);
    }
  }, [product]);

  // Auto-generate SKU when name changes (only for new products, only once)
  useEffect(() => {
    if (!product && formData.name && !formData.sku && !skuAutoGenerated) {
      const generatedSKU = generateSKU(formData.name);
      setFormData(prev => ({ ...prev, sku: generatedSKU }));
      setSkuAutoGenerated(true);
    }
  }, [formData.name, formData.sku, product, skuAutoGenerated]);

  // Filter categories based on input
  useEffect(() => {
    if (formData.category.trim() === '') {
      setFilteredCategories(categories);
    } else {
      const filtered = categories.filter(cat =>
        cat.toLowerCase().includes(formData.category.toLowerCase())
      );
      setFilteredCategories(filtered);
    }
  }, [formData.category, categories]);

  const handleCategorySelect = (category: string) => {
    setFormData(prev => ({ ...prev, category }));
    setShowCategorySuggestions(false);
    categoryInputRef.current?.blur();
  };

  // Handle click outside to close suggestions
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (
        categoryInputRef.current &&
        categoryListRef.current &&
        !categoryInputRef.current.contains(event.target as Node) &&
        !categoryListRef.current.contains(event.target as Node)
      ) {
        setShowCategorySuggestions(false);
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const url = product?._id 
        ? `/api/products/${product._id}?tenant=${tenant}` 
        : `/api/products?tenant=${tenant}`;
      const method = product?._id ? 'PUT' : 'POST';

      const res = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: formData.name,
          description: formData.description,
          price: parseFloat(formData.price),
          stock: parseInt(formData.stock),
          sku: formData.sku || undefined,
          category: formData.category || undefined,
        }),
      });

      const data = await res.json();
      if (data.success) {
        onClose();
      } else {
        alert(data.error || (dict?.products.saveError || 'Failed to save product'));
      }
    } catch (error) {
      console.error('Error saving product:', error);
      alert(dict?.products.saveError || 'Failed to save product');
    } finally {
      setLoading(false);
    }
  };

  if (!dict) {
    return null;
  }

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-lg p-4 sm:p-6 w-full max-w-md max-h-[90vh] overflow-y-auto">
        <h2 className="text-xl sm:text-2xl font-bold mb-4">
          {product ? dict.products.editProduct : dict.products.addProduct}
        </h2>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              {dict.products.name} *
            </label>
            <input
              type="text"
              required
              value={formData.name}
              onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              className="w-full px-3 py-2.5 text-base border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              {dict.products.description}
            </label>
            <textarea
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              className="w-full px-3 py-2.5 text-base border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
              rows={3}
            />
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                {dict.products.price} *
              </label>
              <input
                type="number"
                step="0.01"
                required
                value={formData.price}
                onChange={(e) => setFormData({ ...formData, price: e.target.value })}
                className="w-full px-3 py-2.5 text-base border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                {dict.products.stock} *
              </label>
              <input
                type="number"
                required
                value={formData.stock}
                onChange={(e) => setFormData({ ...formData, stock: e.target.value })}
                className="w-full px-3 py-2.5 text-base border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
              />
            </div>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              {dict.products.sku}
            </label>
            <div className="flex gap-2">
              <input
                type="text"
                value={formData.sku}
                onChange={(e) => {
                  setFormData({ ...formData, sku: e.target.value });
                  setSkuAutoGenerated(false);
                }}
                className="flex-1 px-3 py-2.5 text-base border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
                placeholder={!product ? 'Auto-generated' : ''}
              />
              {!product && (
                <button
                  type="button"
                  onClick={() => {
                    const generatedSKU = generateSKU(formData.name || 'PRO');
                    setFormData(prev => ({ ...prev, sku: generatedSKU }));
                    setSkuAutoGenerated(true);
                  }}
                  className="px-3 py-2.5 bg-gray-100 text-gray-700 rounded-md hover:bg-gray-200 transition-colors text-sm font-medium"
                  title="Regenerate SKU"
                >
                  <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                  </svg>
                </button>
              )}
            </div>
          </div>
          <div className="relative">
            <label className="block text-sm font-medium text-gray-700 mb-1">
              {dict.products.category}
            </label>
            <div ref={categoryInputRef} className="relative">
              <input
                type="text"
                value={formData.category}
                onChange={(e) => {
                  setFormData({ ...formData, category: e.target.value });
                  setShowCategorySuggestions(true);
                }}
                onFocus={() => setShowCategorySuggestions(true)}
                className="w-full px-3 py-2.5 text-base border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
                placeholder="Type to search or select..."
              />
              {showCategorySuggestions && filteredCategories.length > 0 && (
                <div
                  ref={categoryListRef}
                  className="absolute z-10 w-full mt-1 bg-white border border-gray-300 rounded-md shadow-lg max-h-60 overflow-y-auto"
                >
                  {filteredCategories.map((cat, index) => (
                    <button
                      key={index}
                      type="button"
                      onClick={() => handleCategorySelect(cat)}
                      className="w-full text-left px-4 py-2 hover:bg-blue-50 focus:bg-blue-50 focus:outline-none transition-colors"
                    >
                      {cat}
                    </button>
                  ))}
                </div>
              )}
            </div>
          </div>
          <div className="flex flex-col sm:flex-row justify-end gap-2 pt-4">
            <button
              type="button"
              onClick={onClose}
              className="w-full sm:w-auto px-4 py-2.5 border border-gray-300 rounded-md text-gray-700 hover:bg-gray-50 active:bg-gray-100 font-medium"
            >
              {dict.common.cancel}
            </button>
            <button
              type="submit"
              disabled={loading}
              className="w-full sm:w-auto px-4 py-2.5 bg-blue-600 text-white rounded-md hover:bg-blue-700 active:bg-blue-800 disabled:opacity-50 disabled:cursor-not-allowed font-medium"
            >
              {loading ? dict.common.loading : dict.common.save}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

