'use client';

import { useState, useCallback, useEffect } from 'react';
import { showToast } from '@/lib/toast';
import Win8Drawer from '@/components/admin/Win8Drawer';

interface BillingEvent {
  id: string;
  type: string;
  amount: number;
  currency: string;
  description?: string;
  notes?: string;
  transactionId?: string;
  invoiceUrl?: string;
  createdAt: string;
  tenant?: { slug: string; name: string } | null;
}

interface Pagination { page: number; limit: number; total: number; pages: number; }

interface InvoiceItem { id: string; name: string; description?: string; quantity: number; price: number; subtotal: number; }

interface InvoiceDetail {
  id: string;
  invoiceNumber: string;
  status: string;
  dueDate: string;
  paidAt?: string | null;
  paymentTerms?: string | null;
  notes?: string | null;
  subtotal: number;
  discountAmount?: number | null;
  taxAmount: number;
  total: number;
  paidAmount?: number | null;
  createdAt: string;
  tenant?: { slug: string; name: string } | null;
  transaction?: { receiptNumber: string; total: number } | null;
  customer?: { firstName: string; lastName: string; email?: string; phone?: string } | null;
  snapshotName?: string | null;
  snapshotEmail?: string | null;
  items: InvoiceItem[];
}

// Everything BillingEventType can actually be (prisma/schema.prisma) — used
// for the filter dropdown, which must cover system-generated events too.
const ALL_EVENT_TYPES = [
  'invoice_created', 'payment_received', 'payment_failed', 'refund_issued',
  'credit_applied', 'plan_changed', 'trial_started', 'trial_converted',
  'trial_expired', 'subscription_cancelled', 'subscription_suspended',
  'subscription_paused', 'subscription_resumed', 'manual_adjustment',
  'invoice_generated',
];

// Subset an admin can manually record via the form below (the rest are
// system-generated by billing automations and shouldn't be hand-entered).
const RECORDABLE_EVENT_TYPES = [
  'payment_received', 'payment_failed', 'refund_issued',
  'credit_applied', 'manual_adjustment', 'invoice_created',
];

const TYPE_BADGE: Record<string, string> = {
  payment_received: 'bg-win8-success text-white',
  payment_failed: 'bg-win8-danger text-white',
  refund_issued: 'bg-win8-suspended text-white',
  credit_applied: 'bg-win8-info text-white',
  manual_adjustment: 'bg-win8-accent text-white',
  invoice_created: 'bg-gray-500 text-white',
  invoice_generated: 'bg-gray-500 text-white',
  plan_changed: 'bg-win8-accent text-white',
  trial_started: 'bg-win8-warning text-white',
  trial_converted: 'bg-win8-success text-white',
  trial_expired: 'bg-win8-danger text-white',
  subscription_cancelled: 'bg-win8-danger text-white',
  subscription_suspended: 'bg-win8-suspended text-white',
  subscription_paused: 'bg-win8-info text-white',
  subscription_resumed: 'bg-win8-success text-white',
};

export default function BillingPage() {
  const [tenantSlugFilter, setTenantSlugFilter] = useState('');
  const [typeFilter, setTypeFilter] = useState('');
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');

  const [events, setEvents] = useState<BillingEvent[]>([]);
  const [pagination, setPagination] = useState<Pagination>({ page: 1, limit: 20, total: 0, pages: 0 });
  const [loading, setLoading] = useState(false);

  const [invoiceEvent, setInvoiceEvent] = useState<BillingEvent | null>(null);
  const [invoiceDetail, setInvoiceDetail] = useState<InvoiceDetail | null>(null);
  const [invoiceLoading, setInvoiceLoading] = useState(false);
  const [invoiceError, setInvoiceError] = useState('');

  useEffect(() => {
    if (!invoiceEvent?.invoiceUrl) { setInvoiceDetail(null); setInvoiceError(''); return; }
    const match = invoiceEvent.invoiceUrl.match(/^\/invoices\/(.+)$/);
    if (!match) { setInvoiceDetail(null); setInvoiceError(''); return; } // external URL — handled separately below

    const id = match[1];
    setInvoiceLoading(true);
    setInvoiceError('');
    setInvoiceDetail(null);
    fetch(`/api/super-admin/invoices/${id}`, { credentials: 'include' })
      .then((res) => res.json())
      .then((data) => {
        if (data.success) setInvoiceDetail(data.data);
        else setInvoiceError(data.error || 'Invoice not found');
      })
      .catch(() => setInvoiceError('Failed to load invoice'))
      .finally(() => setInvoiceLoading(false));
  }, [invoiceEvent]);

  const [showForm, setShowForm] = useState(false);
  const [formTenantSlug, setFormTenantSlug] = useState('');
  const [formType, setFormType] = useState('payment_received');
  const [formAmount, setFormAmount] = useState('');
  const [formDescription, setFormDescription] = useState('');
  const [formNotes, setFormNotes] = useState('');
  const [formTxId, setFormTxId] = useState('');
  const [formInvoiceUrl, setFormInvoiceUrl] = useState('');
  const [saving, setSaving] = useState(false);

  const fetchEvents = useCallback(async (page: number, limit: number) => {
    setLoading(true);
    try {
      const params = new URLSearchParams({ page: String(page), limit: String(limit) });
      if (tenantSlugFilter) params.set('tenantSlug', tenantSlugFilter);
      if (typeFilter) params.set('type', typeFilter);
      if (startDate) params.set('startDate', startDate);
      if (endDate) params.set('endDate', endDate);

      const res = await fetch(`/api/super-admin/billing?${params}`, { credentials: 'include' });
      const data = await res.json();
      if (data.success) {
        setEvents(data.data);
        setPagination(data.pagination);
      } else {
        setEvents([]);
        showToast.error(data.error || 'Failed to load billing history');
      }
    } catch {
      setEvents([]);
      showToast.error('Failed to load billing history');
    } finally {
      setLoading(false);
    }
  }, [tenantSlugFilter, typeFilter, startDate, endDate]);

  useEffect(() => { fetchEvents(1, pagination.limit); }, [fetchEvents]); // eslint-disable-line react-hooks/exhaustive-deps

  const handleFilterSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    fetchEvents(1, pagination.limit);
  };

  const clearFilters = () => {
    setTenantSlugFilter('');
    setTypeFilter('');
    setStartDate('');
    setEndDate('');
  };

  const openRecordForm = () => {
    setFormTenantSlug(tenantSlugFilter);
    setFormType('payment_received');
    setFormAmount('');
    setFormDescription('');
    setFormNotes('');
    setFormTxId('');
    setFormInvoiceUrl('');
    setShowForm(true);
  };

  const submitEvent = async (e: React.FormEvent) => {
    e.preventDefault();
    const slug = formTenantSlug.trim().toLowerCase();
    if (!slug) { showToast.error('Tenant slug is required'); return; }
    setSaving(true);
    try {
      const res = await fetch(`/api/super-admin/billing/${slug}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({
          type: formType,
          amount: Number(formAmount),
          description: formDescription || undefined,
          notes: formNotes || undefined,
          transactionId: formTxId || undefined,
          invoiceUrl: formInvoiceUrl || undefined,
        }),
      });
      const data = await res.json();
      if (data.success) {
        showToast.success('Billing event recorded');
        setShowForm(false);
        fetchEvents(1, pagination.limit);
      } else {
        showToast.error(data.error || 'Failed to record billing event');
      }
    } catch {
      showToast.error('An error occurred');
    } finally {
      setSaving(false);
    }
  };

  const fmt = (d: string) =>
    new Date(d).toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit' });

  return (
    <>
      <div className="space-y-4">
        <form onSubmit={handleFilterSubmit} className="bg-white border border-gray-300 p-4 flex flex-wrap gap-3 items-end">
          <div>
            <label className="block text-xs font-medium text-gray-600 mb-1">Tenant Slug</label>
            <input
              type="text"
              value={tenantSlugFilter}
              onChange={(e) => setTenantSlugFilter(e.target.value)}
              placeholder="All tenants"
              className="px-3 py-2 border border-gray-300 text-sm w-44 focus:outline-none bg-white"
            />
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-600 mb-1">Type</label>
            <select
              value={typeFilter}
              onChange={(e) => setTypeFilter(e.target.value)}
              className="px-3 py-2 border border-gray-300 text-sm bg-white capitalize w-44"
            >
              <option value="">All types</option>
              {ALL_EVENT_TYPES.map((t) => (
                <option key={t} value={t} className="capitalize">{t.replace(/_/g, ' ')}</option>
              ))}
            </select>
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-600 mb-1">From</label>
            <input
              type="date"
              value={startDate}
              onChange={(e) => setStartDate(e.target.value)}
              className="px-3 py-2 border border-gray-300 text-sm"
            />
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-600 mb-1">To</label>
            <input
              type="date"
              value={endDate}
              onChange={(e) => setEndDate(e.target.value)}
              className="px-3 py-2 border border-gray-300 text-sm"
            />
          </div>
          <button type="submit" className="px-4 py-2 bg-brand text-white text-sm font-medium hover:bg-brand-hover transition-colors">
            Filter
          </button>
          {(tenantSlugFilter || typeFilter || startDate || endDate) && (
            <button type="button" onClick={clearFilters} className="px-3 py-2 text-sm text-gray-500 hover:text-gray-700">
              Clear
            </button>
          )}
          <button
            type="button"
            onClick={openRecordForm}
            className="ml-auto px-4 py-2 border border-gray-300 text-sm text-gray-600 hover:bg-gray-50 bg-white transition-colors"
          >
            + Record Billing Event
          </button>
        </form>

        {loading ? (
          <div className="text-center py-12 bg-white border border-gray-300">
            <div className="win8-spinner text-brand mx-auto">
              <span /><span /><span /><span /><span />
            </div>
            <p className="mt-3 text-gray-500 text-sm">Loading billing events…</p>
          </div>
        ) : events.length === 0 ? (
          <div className="text-center py-12 text-gray-500 bg-white border border-gray-300">No billing events found.</div>
        ) : (
          <div className="overflow-x-auto border border-gray-300 bg-white">
            <table className="w-full text-sm">
              <thead className="bg-brand-navy text-white text-xs uppercase tracking-wide">
                <tr>
                  {['Date', 'Tenant', 'Type', 'Amount', 'Description', 'Transaction ID', 'Invoice'].map((h) => (
                    <th key={h} className="px-4 py-3 text-left font-medium">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {events.map((ev) => (
                  <tr key={ev.id} className="hover:bg-gray-100 transition-colors">
                    <td className="px-4 py-3 text-xs text-gray-500 whitespace-nowrap">{fmt(ev.createdAt)}</td>
                    <td className="px-4 py-3">
                      <p className="text-gray-900 font-medium">{ev.tenant?.name || '—'}</p>
                      <p className="text-xs text-gray-400 font-mono">{ev.tenant?.slug || '—'}</p>
                    </td>
                    <td className="px-4 py-3">
                      <span className={`px-2 py-0.5 text-xs font-semibold capitalize ${TYPE_BADGE[ev.type] || 'bg-gray-500 text-white'}`}>
                        {ev.type.replace(/_/g, ' ')}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-gray-900 font-medium">
                      {ev.currency} {ev.amount.toLocaleString()}
                    </td>
                    <td className="px-4 py-3 text-gray-600 text-xs max-w-[240px] truncate" title={ev.description}>
                      {ev.description || '—'}
                    </td>
                    <td className="px-4 py-3 text-gray-400 font-mono text-xs">{ev.transactionId || '—'}</td>
                    <td className="px-4 py-3">
                      {ev.invoiceUrl ? (
                        <button
                          type="button"
                          onClick={() => setInvoiceEvent(ev)}
                          className="text-brand hover:underline text-xs"
                        >
                          View
                        </button>
                      ) : (
                        <span className="text-gray-400 text-xs">—</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>

            {pagination.pages > 1 && (
              <div className="border-t border-gray-200 px-4 py-3 flex items-center justify-between text-sm text-gray-500">
                <span>Page {pagination.page} of {pagination.pages} ({pagination.total} total)</span>
                <div className="flex gap-2">
                  <button
                    disabled={pagination.page <= 1}
                    onClick={() => fetchEvents(pagination.page - 1, pagination.limit)}
                    className="px-3 py-1 border border-gray-300 disabled:opacity-40 hover:bg-gray-50 bg-white transition-colors"
                  >
                    ← Prev
                  </button>
                  <button
                    disabled={pagination.page >= pagination.pages}
                    onClick={() => fetchEvents(pagination.page + 1, pagination.limit)}
                    className="px-3 py-1 border border-gray-300 disabled:opacity-40 hover:bg-gray-50 bg-white transition-colors"
                  >
                    Next →
                  </button>
                </div>
              </div>
            )}
          </div>
        )}
      </div>

      {invoiceEvent && (
        <div
          className="fixed inset-0 bg-black/40 z-50"
          onClick={() => setInvoiceEvent(null)}
        >
          <div
            className="absolute inset-y-0 right-0 w-full max-w-2xl bg-white border-l border-gray-300 flex flex-col animate-slide-in-right"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center justify-between px-6 py-4 bg-brand-navy text-white shrink-0">
              <div>
                <h2 className="text-base font-semibold">Invoice</h2>
                <p className="text-xs text-white/70 mt-0.5">
                  {invoiceEvent.tenant?.name || invoiceEvent.tenant?.slug} · {invoiceEvent.currency} {invoiceEvent.amount.toLocaleString()} · {fmt(invoiceEvent.createdAt)}
                </p>
              </div>
              <div className="flex items-center gap-4">
                {invoiceEvent.invoiceUrl?.startsWith('http') && (
                  <a
                    href={invoiceEvent.invoiceUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-xs text-white/90 hover:underline"
                  >
                    Open in new tab
                  </a>
                )}
                <button onClick={() => setInvoiceEvent(null)} title="Close" aria-label="Close" className="text-white/70 hover:text-white">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24" aria-hidden="true"><path strokeLinecap="round" strokeLinejoin="round" d="M6 18 18 6M6 6l12 12" /></svg>
                </button>
              </div>
            </div>
            <div className="flex-1 bg-gray-50 overflow-y-auto">
              {!invoiceEvent.invoiceUrl ? (
                <div className="p-6 text-sm text-gray-400">No invoice URL on this event.</div>
              ) : invoiceEvent.invoiceUrl.startsWith('http') ? (
                <iframe src={invoiceEvent.invoiceUrl} title="Invoice" className="w-full h-full border-0" />
              ) : invoiceLoading ? (
                <div className="p-6 text-sm text-gray-400">Loading invoice…</div>
              ) : invoiceError ? (
                <div className="p-6 text-sm text-red-500">{invoiceError}</div>
              ) : invoiceDetail ? (
                <div className="p-6 bg-white m-4 border border-gray-200 space-y-6">
                  <div className="flex items-start justify-between">
                    <div>
                      <p className="text-lg font-bold text-gray-900">Invoice {invoiceDetail.invoiceNumber}</p>
                      <p className="text-sm text-gray-500">{invoiceDetail.tenant?.name || invoiceDetail.tenant?.slug}</p>
                    </div>
                    <span className={`px-2 py-0.5 text-xs font-semibold capitalize ${
                      invoiceDetail.status === 'paid' ? 'bg-win8-success text-white' :
                      invoiceDetail.status === 'overdue' ? 'bg-win8-danger text-white' :
                      invoiceDetail.status === 'sent' ? 'bg-win8-info text-white' :
                      'bg-gray-500 text-white'
                    }`}>
                      {invoiceDetail.status}
                    </span>
                  </div>

                  <div className="grid grid-cols-2 gap-4 text-sm">
                    <div>
                      <p className="text-xs text-gray-400 uppercase tracking-wide mb-0.5">Bill To</p>
                      <p className="text-gray-800">
                        {invoiceDetail.customer
                          ? `${invoiceDetail.customer.firstName} ${invoiceDetail.customer.lastName}`
                          : invoiceDetail.snapshotName || invoiceDetail.tenant?.name || '—'}
                      </p>
                      <p className="text-gray-400 text-xs">{invoiceDetail.customer?.email || invoiceDetail.snapshotEmail || ''}</p>
                    </div>
                    <div>
                      <p className="text-xs text-gray-400 uppercase tracking-wide mb-0.5">Due Date</p>
                      <p className="text-gray-800">{fmt(invoiceDetail.dueDate)}</p>
                      {invoiceDetail.paidAt && <p className="text-win8-success text-xs mt-0.5">Paid {fmt(invoiceDetail.paidAt)}</p>}
                    </div>
                  </div>

                  <table className="w-full text-sm">
                    <thead>
                      <tr className="text-left text-xs text-gray-400 uppercase border-b border-gray-200">
                        <th className="pb-2 font-medium">Item</th>
                        <th className="pb-2 font-medium text-right">Qty</th>
                        <th className="pb-2 font-medium text-right">Price</th>
                        <th className="pb-2 font-medium text-right">Subtotal</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-100">
                      {invoiceDetail.items.map((it) => (
                        <tr key={it.id}>
                          <td className="py-2 text-gray-800">{it.name}</td>
                          <td className="py-2 text-right text-gray-500">{it.quantity}</td>
                          <td className="py-2 text-right text-gray-500">{it.price.toLocaleString()}</td>
                          <td className="py-2 text-right text-gray-800">{it.subtotal.toLocaleString()}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>

                  <div className="border-t border-gray-200 pt-3 space-y-1 text-sm ml-auto max-w-[220px]">
                    <div className="flex justify-between text-gray-500">
                      <span>Subtotal</span><span>{invoiceDetail.subtotal.toLocaleString()}</span>
                    </div>
                    {!!invoiceDetail.discountAmount && (
                      <div className="flex justify-between text-gray-500">
                        <span>Discount</span><span>-{invoiceDetail.discountAmount.toLocaleString()}</span>
                      </div>
                    )}
                    <div className="flex justify-between text-gray-500">
                      <span>
                        VAT
                        {(() => {
                          const taxableBase = invoiceDetail.subtotal - (invoiceDetail.discountAmount || 0);
                          if (taxableBase > 0 && invoiceDetail.taxAmount > 0) {
                            const rate = (invoiceDetail.taxAmount / taxableBase) * 100;
                            return ` (${rate % 1 === 0 ? rate.toFixed(0) : rate.toFixed(1)}%)`;
                          }
                          return '';
                        })()}
                      </span>
                      <span>{invoiceDetail.taxAmount.toLocaleString()}</span>
                    </div>
                    <div className="flex justify-between text-gray-900 font-semibold text-base pt-1 border-t border-gray-200">
                      <span>Total</span><span>{invoiceDetail.total.toLocaleString()}</span>
                    </div>
                    <p className="text-[11px] text-gray-400 text-right pt-0.5">VAT inclusive</p>
                  </div>

                  {invoiceDetail.notes && (
                    <p className="text-xs text-gray-400 border-t border-gray-200 pt-3">{invoiceDetail.notes}</p>
                  )}
                </div>
              ) : null}
            </div>
          </div>
        </div>
      )}

      <Win8Drawer open={showForm} onClose={() => setShowForm(false)}>
        <div className="flex items-center justify-between px-6 py-4 bg-brand-navy text-white shrink-0">
          <h2 className="text-base font-semibold">Record Billing Event</h2>
          <button onClick={() => setShowForm(false)} title="Close" aria-label="Close" className="text-white/70 hover:text-white">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24" aria-hidden="true"><path strokeLinecap="round" strokeLinejoin="round" d="M6 18 18 6M6 6l12 12" /></svg>
          </button>
        </div>
        <form onSubmit={submitEvent} className="flex flex-col flex-1 min-h-0">
          <div className="p-6 space-y-4 overflow-y-auto flex-1 min-h-0">
            <div>
              <label className="block text-xs font-medium text-gray-600 mb-1">Tenant Slug *</label>
              <input
                type="text" required
                value={formTenantSlug}
                onChange={(e) => setFormTenantSlug(e.target.value)}
                className="w-full border border-gray-300 px-3 py-2 text-sm focus:outline-none bg-white"
                placeholder="my-store"
              />
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-600 mb-1">Type *</label>
              <select
                value={formType}
                onChange={(e) => setFormType(e.target.value)}
                className="w-full border border-gray-300 px-3 py-2 text-sm bg-white capitalize focus:outline-none"
              >
                {RECORDABLE_EVENT_TYPES.map((t) => (
                  <option key={t} value={t} className="capitalize">{t.replace(/_/g, ' ')}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-600 mb-1">Amount (₱) *</label>
              <input
                type="number" min="0" step="0.01" required
                value={formAmount}
                onChange={(e) => setFormAmount(e.target.value)}
                className="w-full border border-gray-300 px-3 py-2 text-sm focus:outline-none bg-white"
                placeholder="0.00"
              />
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-600 mb-1">Description</label>
              <input
                value={formDescription}
                onChange={(e) => setFormDescription(e.target.value)}
                className="w-full border border-gray-300 px-3 py-2 text-sm focus:outline-none bg-white"
                placeholder="Optional"
              />
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-600 mb-1">Transaction ID</label>
              <input
                value={formTxId}
                onChange={(e) => setFormTxId(e.target.value)}
                className="w-full border border-gray-300 px-3 py-2 text-sm focus:outline-none bg-white"
                placeholder="Optional"
              />
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-600 mb-1">Invoice URL</label>
              <input
                value={formInvoiceUrl}
                onChange={(e) => setFormInvoiceUrl(e.target.value)}
                className="w-full border border-gray-300 px-3 py-2 text-sm focus:outline-none bg-white"
                placeholder="Optional"
              />
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-600 mb-1">Notes</label>
              <textarea
                value={formNotes}
                onChange={(e) => setFormNotes(e.target.value)}
                rows={2}
                className="w-full border border-gray-300 px-3 py-2 text-sm resize-none focus:outline-none bg-white"
                placeholder="Optional"
              />
            </div>
          </div>
          <div className="flex gap-3 px-6 py-4 border-t border-gray-200 justify-end shrink-0">
            <button type="button" onClick={() => setShowForm(false)} className="px-4 py-2 border border-gray-300 text-gray-700 bg-white text-sm hover:bg-gray-50 transition-colors">
              Cancel
            </button>
            <button
              type="submit"
              disabled={saving || !formAmount || !formTenantSlug.trim()}
              className="px-4 py-2 bg-brand text-white text-sm font-semibold hover:bg-brand-hover disabled:opacity-50 transition-colors"
            >
              {saving ? 'Saving…' : 'Record Event'}
            </button>
          </div>
        </form>
      </Win8Drawer>
    </>
  );
}
